//criando tabelas:

create table pacientes(
id int primary key,
nome varchar(50),
dt_nascimento varchar(10),
telefone varchar(12)
);

create table profissionais(
matricula int primary key,
nome varchar(50),
cargo varchar(50),
departamento varchar(60),
telefone varchar(12)
);

create table internações(
id_internações int,
id_pacientes int,
entrada_data_hora varchar(14),
saída_data_hora varchar(14),
diagnóstico varchar(100),
matricula_profissionais int,
primary key(id_internações, id_pacientes),
constraint fk_pacientes
foreign key(id_pacientes)
references pacientes(id),
constraint fk_profissionais
foreign key(matricula_profissionais)
references profissionais(matricula)
);

alter table pacientes 
alter column id
  add generated by default as identity
  
  select *from pacientes p
  
  
//Inserindo dados nas tabelas:

insert into pacientes 
(nome, dt_nascimento, telefone)
values 
('Jair', '21/03/1955', '1191234-5678'),
('Carla', '03/07/1968', '1181122-3344'),
('Daniel', '25/11/1973', '1172332-6543')

alter table pacientes  
alter column id
  add generated by default as identity

select *from pacientes p 

insert into profissionais
(nome,cargo,departamento,telefone)
values 
('Alexandre', 'médico', 'cardiologia', '1198989-1000'),
('Roberto', 'médico', 'clínica', '1187878-2000'),
('Carmem', 'enfermeira', 'cardiologia', '1177887-3000'),
('Maria', 'médica', 'uti', '1195959-4000'),
('Edson', 'farmaceutico', 'farmácia', '1184848-5000')

alter table profissionais  
alter column matricula
  add generated by default as identity
  
  select *from profissionais p  

insert into internações
(id_pacientes, entrada_data_hora, saída_data_hora, diagnóstico , matricula_profissionais)
values
(1, '25/01/2006 11h', '30/01/2006 18h', 'arritimia', 1)

alter table internações   
alter column id_internações
  add generated by default as identity

insert into internações 
(id_pacientes, entrada_data_hora, saída_data_hora, diagnóstico , matricula_profissionais)
values
(1, '17/07/2012 8h', '24/07/2012 14h', 'insuficiência cardiaca', 4)

insert into internações 
(id_pacientes, entrada_data_hora, saída_data_hora, diagnóstico , matricula_profissionais)
values
(1, '08/08/2020 9h', '18/08/2020 15h', 'cirurgia cardiaca', 3),
(2, '10/04/2019 12h', '12/04/2019 18h', 'infecção pulmonar', 4),
(2, '06/09/2020 10h', '14/09/2020 15h', 'cirurgia cardiaca', 1),
(3, '11/12/2021 17h', '13/12/2021 15h', 'obstrução intestinal', 2)

select *from internações i 

delete from internações 

drop table internações 


//Agrupamento da quantidade de internações em ordenamento decrescente:

select i.id_pacientes as id_paciente, p.nome, count (p.nome) as qtd_internações
from internações i 
inner join pacientes p  
on i.id_pacientes = p.id 
group by id_pacientes , p.nome 
order by qtd_internações desc


//Adicionando mais médicos:

insert into profissionais
(nome,cargo,departamento,telefone)
values
('Ricardo', 'médico', 'cardiologia', '1190001-6000'),
('José Antonio', 'médico', 'cardiologia', '1190002-7000'),
('Gilmar', 'médico', 'uti', '1190003-8000')

//Alreando o nome cargo da matrícula 4 para médico:

update profissionais 
set cargo = 'médico'
where matricula = 4

//Agrupamento da quantidade de médicos por departmente em ordenamento decrescente:

select  p.cargo as cargo, p.departamento, count(p.departamento) as qtd_médicos
from profissionais p 
where p.cargo like 'médic%'
group by p.cargo , p.departamento 
order by qtd_médicos desc 


